### ISSUE TITLE
Fix WalletConnect transaction state issue

### ISSUE THREAD

**Issue by zakangelle** [R-Group-Devs/morphs-nft-frontend#1]
See https://github.com/tmm/wagmi/issues/116 for more details.

**Comment by zakangelle** [comment]
Closing as this only happens on non-mainnet networks.

**Comment by zakangelle** [comment]
@rcstanciu The Morphs app supports Rinkeby testnet and Ethereum mainnet. The [bug](https://github.com/tmm/wagmi/issues/116) surfaces when using Rinkeby -- it will still allow you to mint, but will not show a "Minting..." message (when transaction is pending) and "Success" message (when transaction is confirmed).

**Comment by rcstanciu** [comment]
And on mainnet the bug does not happen at all? The promises return as they should, like with the regular `InjectedConnector`?

**Comment by zakangelle** [comment]
@rcstanciu Exactly, it has to do with the `HttpProvider` for the `WalletConnectConnector` being mistakenly instantiated with `chainId: 1`, which works fine when you're using mainnet, but causes this bug on other networks. I tested on mainnet after launch and didn't see the bug -- are you seeing something different?

**Comment by rcstanciu** [comment]
Thanks to you, I looked at the source code of WalletConnect connector and found a workaround. If you set the `chainId` to the working network, in the options object when instantiating the WalletConnectConnector, it will work. I'm not sure if it will still work after some network changes but it's a start haha.

**Comment by zakangelle** [comment]
@rcstanciu Nice! I'll have to try that out. Curious if it works w/ switching networks after initial load.
